### PR TITLE
Fix Garbage Collector Abuse

### LINKED ISSUE #5: End garbage collector abuse
We're currently creating objects in some execute methods. Let's not do that, since it's garbage collector abuse and will also legit cause loop overruns.

### PR DESCRIPTION
**Pull request by QuackitsQuinn**
Fix the redundant creation of an empty Translation2d. Unfortunately due to the immutability of Translation2d, this is all I could do without doing gross reflection stuff that would cause more of the issue this attempts to fix.

Closes #5

### CODE REVIEW

File: src/main/java/frc/robot/subsystems/Drive.java [hunk 1]
```diff
@@ -24,6 +24,9 @@
 public class Drive extends SubsystemBase {
   SwerveDrive drive;
 
+  /** Empty translation to prevent creating 2 Translation2ds per periodic run */
+  private static final Translation2d EMPTY_TRANSLATION = new Translation2d();
```
Comment (willitcode) [inline src/main/java/frc/robot/subsystems/Drive.java:28]: Let's create a Drive subclass of Constants and slap that in there instead.

**Review by willitcode — CHANGES_REQUESTED** [review]

**Review by willitcode — APPROVED** [review]
Looks good! Thanks
