### PR TITLE
Fix the last of the formatting issues.

### LINKED ISSUE #2: Comply with Team 937 formatting
- Yeet Hungarian Notation
- Make subsystems `public static` (and get rid of dependency injection)
- Rename `Constants.OperatorConstants` to `Constants.Driver`

### PR DESCRIPTION
**Pull request by quackitsquinn**
Fix the last of Hungarian Notation and add a missing access modifier. Fixes #2.

### CODE REVIEW

File: src/main/java/frc/robot/subsystems/Drive.java [hunk 1]
```diff
@@ -23,7 +23,7 @@
 import swervelib.parser.SwerveParser;
 
 public class Drive extends SubsystemBase {
-  SwerveDrive drive;
+  private SwerveDrive drive;
```
Comment (willitcode) [inline src/main/java/frc/robot/subsystems/Drive.java:26]: `private final` I think

**Review by willitcode — CHANGES_REQUESTED** [review]

File: src/main/java/frc/robot/subsystems/Drive.java (hunk 1 above)
Comment (QuackitsQuinn) [reply src/main/java/frc/robot/subsystems/Drive.java:26]: Because of the weird try/catch clause, this isn't super viable.

Comment (willitcode) [reply src/main/java/frc/robot/subsystems/Drive.java:26]: gotcha, resolving

**Review by willitcode — APPROVED** [review]
